# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print('list(a): ', list(a))
print('list只有轉第一層')
print('tolist(): ', a.tolist())
print('tolist將每層array轉成list')

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
list只有轉第一層
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
tolist將每層array轉成list


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [3]:
# 記得先 Import 正確的套件
import numpy as np


In [9]:

a = np.random.randint(10, size=6) 
print(a)
print(a.ndim) #維度
print(a.shape) #每個維度大小
print(a.size) #陣列當中有幾個元素
print(a.dtype) #陣列元素資料型態
print(a.itemsize) #陣列中每個元素佔用的空間
print(len(a)) #陣列長度
print(type(a)) #陣列資料型態


[0 0 8 7 9 1]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [11]:
b = np.random.randint(10, size=(3,4)) 
print()
print(b.ndim) #維度
print(b.shape) #每個維度大小
print(b.size) #陣列當中有幾個元素
print(b.dtype) #陣列元素資料型態
print(b.itemsize) #陣列中每個元素佔用的空間
print(len(b)) #陣列長度
print(type(b)) #陣列資料型態

[[5 6 2 9]
 [3 3 7 4]
 [7 9 2 4]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [12]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim) #維度
print(c.shape) #每個維度大小
print(c.size) #陣列當中有幾個元素
print(c.dtype) #陣列元素資料型態
print(c.itemsize) #陣列中每個元素佔用的空間
print(len(c)) #陣列長度
print(type(c)) #陣列資料型態

[[[8 2]
  [1 0]
  [3 4]]

 [[0 2]
  [1 5]
  [2 4]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [4]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[0, 9, 2, 2, 1, 9]
[0, 9, 2, 2, 1, 9]


In [5]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 1, 2, 5], [3, 7, 9, 8], [7, 8, 3, 5]]
[array([5, 1, 2, 5]), array([3, 7, 9, 8]), array([7, 8, 3, 5])]


In [6]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[8, 9], [9, 0], [8, 5]], [[3, 7], [3, 3], [8, 9]]]
[array([[8, 9],
       [9, 0],
       [8, 5]]), array([[3, 7],
       [3, 3],
       [8, 9]])]


In [13]:
def tolist(iterable):
    return iterable.tolist()

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 0, 8, 7, 9, 1]
[[5, 6, 2, 9], [3, 3, 7, 4], [7, 9, 2, 4]]
[[[8, 2], [1, 0], [3, 4]], [[0, 2], [1, 5], [2, 4]]]


# 延伸題

作業目標:<br>
在array中，可以靈活應用索引幫助資料擷取<br>
作業重點:<br>
陣列的索引、切片、以及屬性，皆需要注意使用方式<br>
陣列之中索引式由0開始請同學注意

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>

In [2]:
import numpy as np

In [6]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a = np.arange(0, 21, 1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [12]:
#2.呈上題，將以上數列取出偶數。
b = np.arange(0, 21, 2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
#3.呈1題，將數列取出3的倍數。
c = np.arange(0, 21, 3)
c

array([ 0,  3,  6,  9, 12, 15, 18])