# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [4]:
import numpy as np

print(np.zeros((2, 3)))
#呼叫 zeros()可以依照傳入的形狀引數，建立元素全為 0的陣列
print(np.empty((2, 3)))
#使用 empty() 函式則是不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [5]:
# 記得先 Import 正確的套件
import numpy as np

In [11]:
# 參考解答
a = np.random.rand(2, 3)
q = np.round(a)
q

array([[0., 1., 1.],
       [1., 0., 0.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [14]:
m = 20
n = 40

x = np.random.randint(m, n, size=(2,3))
x

array([[39, 22, 21],
       [33, 20, 24]])

# 延伸作業

作業目標

在一個陣列中放入多屬性陣列，進一步對陣列做運算

作業重點

在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性


題目:

name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']

sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']

weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]

rank_list = [8,1,5,4,7,6,2,3]

myopia_list = [True,True,False,False,True,True,False,False]

將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

呈上題，將array中體重(weight)數據集取出算出全部平均體重

呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [15]:
import numpy as np 

In [16]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [22]:
#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
dt=np.dtype({"names":("name", "sex", "weight", "rank", "myopia"), "formats":((np.str_, 8), (np.str_, 8),float,int, np.bool_)})
a = np.empty(8,dtype=dt)
a['name'] = name_list
a['sex'] = sex_list
a['weight'] = weight_list
a['rank'] = rank_list 
a['myopia'] = myopia_list
a

array([('小明', 'boy', 67.5, 8,  True), ('小華', 'boy', 75.3, 1,  True),
       ('小菁', 'girl', 50.1, 5, False), ('小美', 'girl', 45.5, 4, False),
       ('小張', 'boy', 80.8, 7,  True), ('John', 'boy', 90.4, 6,  True),
       ('Mark', 'boy', 78.4, 2, False), ('Tom', 'boy', 70.7, 3, False)],
      dtype=[('name', '<U8'), ('sex', '<U8'), ('weight', '<f8'), ('rank', '<i4'), ('myopia', '?')])

In [24]:
#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
sum(a['weight']) / 8.0

69.8375

In [28]:
#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重 
print(np.mean(a[a["sex"]=="boy"]["weight"]))

77.18333333333332


In [29]:
#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重
print(np.mean(a[a["sex"]=="girl"]["weight"]))

47.8
