# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [10]:
a = np.arange(11)
a[3:7]*=-1
a

array([ 0,  1,  2, -3, -4, -5, -6,  7,  8,  9, 10])

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [27]:
A = np.random.rand(3, 6)
print(A)
print(np.sum(A>0.5))

[[0.83265022 0.16460603 0.76389252 0.29916331 0.40544817 0.15655889]
 [0.19690944 0.94581277 0.52695169 0.35056705 0.7199954  0.71697924]
 [0.55573239 0.23059614 0.72133979 0.753354   0.61530153 0.16373782]]
10


# 延伸題

作業目標

計算有缺失值的資料，統計量實作

作業重點

當遇到缺失值有函式可以處理，不須額外寫程式刪除

計算統計量時不能出現缺失值

題目:

english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60])

chinese_score = np.array([65,90,82,72,66,77])

上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考

試，導致數學成績缺值，運用上列數據回答下列問題。

請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

用補考後資料找出與國文成績相關係數最高的學科?

In [28]:
import numpy as np

In [29]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [47]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
print("英文")
print(np.mean(english_score)) 
print(np.max(english_score))
print(np.min(english_score))
print(np.std(english_score))
print("數學")
print(np.nanmean(math_score))
print(np.nanmax(math_score))
print(np.nanmin(math_score))
print(np.nanstd(math_score))
print("國文")
print(np.mean(chinese_score)) 
print(np.max(chinese_score))
print(np.min(chinese_score))
print(np.std(chinese_score))

英文
67.16666666666667
89
48
13.433995020924426
數學
66.6
85.0
60.0
9.707728879609279
國文
75.33333333333333
90
65
8.825468196582484


In [49]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[4] = 55
print(np.mean(math_score))
print(np.max(math_score))
print(np.min(math_score))
print(np.std(math_score))

64.66666666666667
85.0
55.0
9.860132971832694


In [54]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
print(np.corrcoef(chinese_score,math_score))
print(np.corrcoef(chinese_score,english_score))
#英文

[[1.         0.74056803]
 [0.74056803 1.        ]]
[[1.         0.97792828]
 [0.97792828 1.        ]]
