# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np
a = np.arange(6)

print(a.sum())  #統計方法
print(np.sum(a)) #同上
print(sum(a)) #用軸去做加總


15
15
15


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [7]:
A = np.random.random((5, 5))
print(A)
print()
print(A/np.linalg.norm(A))

[[0.85816842 0.02952366 0.70604349 0.90656762 0.89081725]
 [0.8076596  0.92090245 0.51025244 0.1719821  0.55591139]
 [0.98265407 0.19745044 0.41975918 0.33829643 0.40230384]
 [0.76293641 0.69439753 0.70856892 0.14213221 0.71075342]
 [0.5829286  0.78961086 0.71896224 0.34608019 0.2543969 ]]

[[0.26917752 0.00926054 0.22146124 0.28435867 0.27941833]
 [0.25333467 0.28885501 0.16004841 0.05394479 0.17437003]
 [0.30822434 0.06193332 0.13166383 0.1061118  0.12618869]
 [0.23930656 0.2178083  0.22225338 0.04458192 0.22293858]
 [0.18284439 0.24767341 0.2255134  0.1085533  0.07979544]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [13]:
a = np.random.random(10)
print(a)
a[a == np.max(a)] = -1
print(a)

[0.89457774 0.48977171 0.55095333 0.22077192 0.91963094 0.23343391
 0.6126276  0.48666371 0.27068522 0.69928992]
[ 0.89457774  0.48977171  0.55095333  0.22077192 -1.          0.23343391
  0.6126276   0.48666371  0.27068522  0.69928992]
